spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:ecom-test
    username: sa
    driver-class-name: org.h2.Driver
    initialization-mode: always
  data:
    mongodb:
      host: 'localhost'
      port: 27017
      database: 'test'
ecom:
  jwt:
    issuer: 'ecom-api'
    expiracao: 360
    chavesecreta: 'secret'