spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/db_ecom
    username: ${USER_DATABASE}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: never
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
ecom:
  jwt:
    issuer: ${TOKEN_ISSUER}
    expiracao: ${TOKEN_EXPIRATION}
    chavesecreta: ${TOKEN_SECRET}