name: Build da aplicação

on: [push]

jobs:
  testes:
    name: Testes Unitários
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Testes
        run: mvn -B test
  push_docker_hub:
    needs: testes
    name: Push da imagem no Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build e push para o Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jamesbotelho/ecom-api:latest